/*
 * BlogBackupForm.java
 *
 * Created on 2007年7月22日
 */

package tenyi.util.html;

import org.htmlparser.util.ParserException;

/**
 *
 * @author  Tenyi
 */
public class BlogBackupForm extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form BlogBackupForm */
    public BlogBackupForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jcbBSP = new javax.swing.JComboBox();
        jtfBlogName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbGo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNoPerPage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfDirectory = new javax.swing.JTextField();
        jbChoostDirectory = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jcbSaveType = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jtfBlogURL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blog \u5099\u4efd");
        jcbBSP.setFont(new java.awt.Font("新細明體", 0, 16));
        jcbBSP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto", "Xuite", "Wretch" }));

        jtfBlogName.setFont(new java.awt.Font("新細明體", 0, 16));
        jtfBlogName.setText("network");

        jLabel1.setFont(new java.awt.Font("新細明體", 0, 16));
        jLabel1.setText("Blog\u7a2e\u985e");

        jLabel2.setFont(new java.awt.Font("新細明體", 0, 16));
        jLabel2.setText("Blog\u540d");

        jbGo.setFont(new java.awt.Font("新細明體", 0, 16));
        jbGo.setText("\u5099\u4efd");
        jbGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("新細明體", 0, 20));
        jLabel3.setText("Blog \u5099\u4efd");

        jLabel4.setFont(new java.awt.Font("新細明體", 0, 16));
        jLabel4.setText("\u6bcf\u9801\u7bc7\u6578");

        jtfNoPerPage.setFont(new java.awt.Font("新細明體", 0, 16));
        jtfNoPerPage.setText("20");
        jtfNoPerPage.setToolTipText("\u5e7e\u7bc7\u5206\u6210\u4e00\u9801");

        jLabel5.setFont(new java.awt.Font("新細明體", 0, 16));
        jLabel5.setText("\u5132\u5b58\u76ee\u9304");

        jtfDirectory.setFont(new java.awt.Font("新細明體", 0, 16));
        jtfDirectory.setText("C:\\");

            jbChoostDirectory.setText("...");
            jbChoostDirectory.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jbChoostDirectoryActionPerformed(evt);
                }
            });

            jLabel6.setFont(new java.awt.Font("新細明體", 0, 16));
            jLabel6.setText("\u5132\u5b58\u683c\u5f0f");

            jcbSaveType.setFont(new java.awt.Font("新細明體", 0, 16));
            jcbSaveType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RSS", "MT" }));

            jLabel7.setFont(new java.awt.Font("新細明體", 0, 16));
            jLabel7.setText("Blog \u7db2\u5740");

            jtfBlogURL.setFont(new java.awt.Font("新細明體", 0, 16));
            jtfBlogURL.setText("http://blog.xuite.net/efchang/network");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addComponent(jbGo)))
                    .addContainerGap())
                .addGroup(layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfNoPerPage, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtfBlogURL, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                                            .addComponent(jtfDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbChoostDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jcbSaveType, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbBSP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfBlogName, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)))))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel3)
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jcbBSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtfBlogName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jtfBlogURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(22, 22, 22)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtfNoPerPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jbChoostDirectory)
                        .addComponent(jtfDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jcbSaveType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addComponent(jbGo)
                    .addGap(31, 31, 31))
            );
            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jbChoostDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChoostDirectoryActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jbChoostDirectoryActionPerformed

    private void jbGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGoActionPerformed
// TODO add your handling code here:
        String blogtype = (String) jcbBSP.getSelectedItem();
        String blogname = jtfBlogName.getText();
        String url = jtfBlogURL.getText();
        String numberperpage = jtfNoPerPage.getText();
        String directory = jtfDirectory.getText();
        String savetype = (String) jcbSaveType.getSelectedItem();
    	BlogExtractor be = new BlogExtractor();
        try {
			be.go(blogtype, blogname, url);
		} catch (ParserException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_jbGoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlogBackupForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbChoostDirectory;
    private javax.swing.JButton jbGo;
    private javax.swing.JComboBox jcbBSP;
    private javax.swing.JComboBox jcbSaveType;
    private javax.swing.JTextField jtfBlogName;
    private javax.swing.JTextField jtfBlogURL;
    private javax.swing.JTextField jtfDirectory;
    private javax.swing.JTextField jtfNoPerPage;
    // End of variables declaration//GEN-END:variables
    
}
